---

# Warning! This file is open source and available in the Internet! Do not add
# any real secrets here! These are for local Vagrant and for reference.

secret:
  exposed_secrets: True
  database_ckan_password: pass
  ckan_admin_password: adminadmin
  ckan_test_password: testtest
  ckan_paha_password: pahapaha
  ckan_harvest_password: harvestharvest
  ckan_config:
    beaker_session_secret: MOMiw^VRo2M@^*lV5^00a2CxDNvB5x
    app_instance_uuid: "{0f13d611-1765-4962-b2af-875bd1a066a2}"
  ckan_harvester_status_email_recipients:
    - "vagrant@localhost"
  ckan_fault_recipients:
    - "vagrant@localhost"
  ckan_harvester_instruction_url: "http://example.com"
  analytics_auth_token: ""
